name: Concatenate Files on Merge

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  merge-sources:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Clean and create output directory
      run: |
        rm -rf output
        mkdir -p output
      shell: bash

    - name: Concatenate files
      run: |
        find Sources/Development -type f -name '*.swift' -exec cat {} + > Sources/PropertyPicker/PropertyPicker.swift
      shell: bash

    # - name: Remove multiline pattern
    #   run: |
    #     awk '
    #     BEGIN { 
    #       p = 0
    #       first_header = 1
    #       first_import = 1
    #     }
    #     # Match the start pattern with a flexible year and name
    #     /^\/\/  Copyright \(c\) [0-9]{4} [A-Za-z ]+/ {
    #       if (first_header) {
    #         first_header = 0
    #         print
    #         next
    #       }
    #       p = 1
    #     }
    #     # Handle import statement
    #     /^import SwiftUI/ {
    #       if (first_import) {
    #         first_import = 0
    #         print
    #         next
    #       }
    #       if (p) {
    #         p = 0
    #         next
    #       }
    #     }
    #     # If flag is set, skip lines; otherwise, print lines
    #     !p' Sources/PropertyPicker/PropertyPicker.swift > temp && mv temp Sources/PropertyPicker/PropertyPicker.swift
    #   shell: bash
      
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Sources/PropertyPicker/PropertyPicker.swift
        git commit -m "Concatenate files for main branch"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}