name: Concatenate Files on Merge

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  merge-sources:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Clean and create output directory
      run: |
        rm -rf output
        mkdir -p output
      shell: bash

    - name: Concatenate files
      run: |
        find Sources/Development -type f -name '*.swift' -exec cat {} + > Sources/PropertyPicker/PropertyPicker.swift
      shell: bash

    - name: Remove multiline pattern
      run: |
        awk '
        BEGIN { 
          p = 0 
          # Define patterns for matching copyright block
          pattern_start = "/^\/\/  Copyright \\(c\\) [0-9]{4} [A-Za-z ]+/"
          pattern_end = "/^import SwiftUI/"
        }
        # Match the start pattern with a flexible year and name
        /^\/\/  Copyright \(c\) [0-9]{4} [A-Za-z ]+/ { 
          p = 1 
        }
        # Reset flag if end pattern is found
        /^import SwiftUI/ { 
          p = 0 
        }
        # If flag is set, skip lines; otherwise, print lines
        p == 0' Sources/PropertyPicker/PropertyPicker.swift > temp && mv temp Sources/PropertyPicker/PropertyPicker.swift
      shell: bash
      
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Sources/PropertyPicker/PropertyPicker.swift
        git commit -m "Concatenate files for main branch"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}