name: Concatenate Files on Merge

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  merge-sources:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Clean and create output directory
      run: |
        rm -rf output
        mkdir -p output
      shell: bash

    - name: Concatenate files
      run: |
        find Sources/PropertyPicker -type f -name '*.swift' -exec cat {} + > PropertyPicker.swift
      shell: bash

    - name: Reorder, sort, and remove duplicate imports
      run: |
        # Extract, sort, and remove duplicates from import statements
        awk '/^import / {print}' PropertyPicker.swift | sort | uniq > sorted_unique_imports.txt

        # Remove import statements from the original file
        awk '!/^import /' PropertyPicker.swift > temp_no_imports.txt

        # Concatenate sorted and unique imports with the rest of the file
        cat sorted_unique_imports.txt temp_no_imports.txt > PropertyPicker.swift

        # Clean up temporary files
        rm sorted_unique_imports.txt temp_no_imports.txt
      shell: bash
      
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add PropertyPicker.swift
        git commit -m "Concatenate files for main branch"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}